packages:
  - 'apps/*'

catalogs:
  frontend:
    "vue": "^3.5.22"

  infra:
    "@typescript-eslint/eslint-plugin": "^8.46.1"
    "@typescript-eslint/parser": "^8.46.1"
    "@zjutjh/eslint-config": "^0.8.0"
    "eslint": "^9.38.0"
    "eslint-config-prettier": "^10.1.8"
    "eslint-plugin-format": "^1.0.2"
    "eslint-plugin-prettier": "^5.5.4"
    "eslint-plugin-vue": "^10.5.1"
    "jiti": "^2.6.1"
    "prettier": "^3.6.2"
    "typescript": "~5.9.3"
    "vue-eslint-parser": "^10.2.0"
    "vue-tsc": "^3.1.0"