packages:
  - 'apps/*'

catalogs:
  frontend:
    "@csstools/normalize.css": "^12.1.1"
    "@vueuse/core": "^13.9.0"
    "lodash-es": "^4.17.21"
    "vue": "^3.5.22"
    "vue-router": "^4.6.3"

  types:
    "@types/lodash-es": "^4.17.12"
    "@types/node": "^24.6.0"

  infra:
    "@typescript-eslint/eslint-plugin": "^8.46.1"
    "@typescript-eslint/parser": "^8.46.1"
    "@zjutjh/eslint-config": "^0.8.0"
    "eslint": "^9.38.0"
    "eslint-config-prettier": "^10.1.8"
    "eslint-plugin-format": "^1.0.2"
    "eslint-plugin-prettier": "^5.5.4"
    "eslint-plugin-vue": "^10.5.1"
    "jiti": "^2.6.1"
    "prettier": "^3.6.2"
    "simple-git-hooks": "^2.1.0"
    "typescript": "~5.9.3"
    "vue-eslint-parser": "^10.2.0"
    "vue-tsc": "^3.1.0"