packages:
  - "apps/*"
  - "packages/*"

catalogs:
  frontend:
    "@csstools/normalize.css": "^12.1.1"
    "@tanstack/vue-query": "^5.92.9"
    "@vueuse/core": "^14.2.0"
    "axios": "^1.13.4"
    "dayjs": "^1.11.19"
    "lodash-es": "^4.17.23"
    "pinia": "^3.0.4"
    "vue": "^3.5.27"
    "vue-router": "^5.0.2"

  types:
    "@types/lodash-es": "^4.17.12"
    "@types/node": "^24.10.10"
    "type-fest": "^5.4.4"

  infra:
    "@typescript-eslint/eslint-plugin": "^8.54.0"
    "@typescript-eslint/parser": "^8.54.0"
    "@vue/tsconfig": "^0.8.1"
    "@zjutjh/eslint-config": "^0.8.0"
    "eslint": "^9.39.2"
    "eslint-config-prettier": "^10.1.8"
    "eslint-plugin-format": "^1.3.1"
    "eslint-plugin-prettier": "^5.5.5"
    "eslint-plugin-vue": "^10.7.0"
    "jiti": "^2.6.1"
    "prettier": "^3.8.1"
    "simple-git-hooks": "^2.13.1"
    "typescript": "~5.9.3"
    "vue-eslint-parser": "^10.2.0"
    "vue-tsc": "^3.2.4"
